# Generated by Django 5.0.6 on 2024-05-14 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='promotions',
            field=models.BooleanField(default=False, verbose_name='promotions'),
        ),
    ]
