# Generated by Django 5.0.6 on 2024-05-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, verbose_name='username'),
        ),
    ]
